name: caroussel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.3.0
  video_player: ^2.9.3
  
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new: ^1.5.0
  flutter_image_compress: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
