// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSVPL78u7QKMaBq1kzm2hyo3KEuIGFjw',
    appId: '1:589160154476:web:5bd09740a85c15cb64df49',
    messagingSenderId: '589160154476',
    projectId: 'carrousel-test',
    authDomain: 'carrousel-test.firebaseapp.com',
    storageBucket: 'carrousel-test.firebasestorage.app',
    measurementId: 'G-FEQV6N3SG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDAUsNkC5nwkX8xVqT8eoMj_nPSI-rPA',
    appId: '1:589160154476:android:f4ace17d1790f57b64df49',
    messagingSenderId: '589160154476',
    projectId: 'carrousel-test',
    storageBucket: 'carrousel-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Lyo2l1rbwxRM-_jL_sObxyPQ6DToNO8',
    appId: '1:589160154476:ios:9f58242295bc219864df49',
    messagingSenderId: '589160154476',
    projectId: 'carrousel-test',
    storageBucket: 'carrousel-test.firebasestorage.app',
    iosBundleId: 'com.example.caroussel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Lyo2l1rbwxRM-_jL_sObxyPQ6DToNO8',
    appId: '1:589160154476:ios:9f58242295bc219864df49',
    messagingSenderId: '589160154476',
    projectId: 'carrousel-test',
    storageBucket: 'carrousel-test.firebasestorage.app',
    iosBundleId: 'com.example.caroussel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArSVPL78u7QKMaBq1kzm2hyo3KEuIGFjw',
    appId: '1:589160154476:web:17523c4d0f0d0ea464df49',
    messagingSenderId: '589160154476',
    projectId: 'carrousel-test',
    authDomain: 'carrousel-test.firebaseapp.com',
    storageBucket: 'carrousel-test.firebasestorage.app',
    measurementId: 'G-6J5M7QVEB1',
  );

}